import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // This matches the 'sidebarId' in your config file
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  troubleshootingSidebar: [{type: 'autogenerated', dirName: 'troubleshooting'}],
  adrsSidebar: [{type: 'autogenerated', dirName: 'adrs'}],
};

export default sidebars;